// English Start Profile — Этап 10: ПРОМЕЖУТОЧНАЯ ДИАГНОСТИКА (Progress
// Check) — Form B банка заданий.
//
// ТЗ Этапа 10: "Не использовать те же задания, что были в Start
// Diagnostic. Создать эквивалентную форму... Обе формы проверяют одни
// и те же навыки и сопоставимую сложность." Это Form B — те же 4
// навыка (Grammar/Vocabulary/Reading/Listening), тот же объём (12
// грамматики + 10 лексики + 2×3 чтения + 2×2 аудирования = 32 задания)
// и та же раскладка уровней/сложности задание-в-задание, что и Form A
// (см. itemBank.ts) — но полностью другой контент (другие
// грамматические примеры, другие тексты), чтобы студент не мог просто
// вспомнить правильный ответ с первого прохождения.
//
// Типы и приём (правильный ответ никогда не сериализуется клиенту,
// см. publicView.ts) — переиспользованы из itemBank.ts без изменений.
import type { DiagnosticItem, DiagnosticPassage } from "./itemBank";

export const DIAGNOSTIC_PASSAGES_B: DiagnosticPassage[] = [
  {
    id: "b-reading-library-orientation",
    skill: "READING",
    contextType: "educational",
    titleRu: "Текст 1 — объявление библиотеки",
    contentEn:
      "The main library is holding an orientation session for new students on Thursday at 3 pm. Students who attend will learn how to search the catalogue, borrow books, and use the study rooms on the second floor. Anyone who cannot attend on Thursday can book a short individual tour at the front desk instead. The library is open from 8 am to 9 pm on weekdays, and until 6 pm on Saturdays. Students must bring their student card to borrow any books.",
  },
  {
    id: "b-reading-company-expansion",
    skill: "READING",
    contextType: "professional",
    titleRu: "Текст 2 — новость о компании",
    contentEn:
      "Silverline Logistics announced this week that it is opening two new distribution centres, one in the north and one in the south of the country. The company's CEO said the expansion was necessary because customer demand has grown faster than expected over the past two years. The new centres are expected to create about 150 jobs in total. However, some analysts have warned that rising fuel costs could make the expansion more expensive than originally planned, and the company may need additional investment next year.",
  },
  {
    id: "b-listening-library-hours",
    skill: "LISTENING",
    contextType: "educational",
    titleRu: "Аудио 1 — объявление об изменении часов работы",
    contentEn:
      "Attention, students. Please note that the library will close early today, at 5 pm instead of 9 pm, because of a staff meeting. The self-service book return will still be available at the entrance. Normal opening hours will resume tomorrow. If you need help finding a book today, please ask a librarian before 4:30 pm, when the help desk closes.",
  },
  {
    id: "b-listening-accountant",
    skill: "LISTENING",
    contextType: "professional",
    titleRu: "Аудио 2 — рассказ о работе",
    contentEn:
      "Hello, my name is Marcus, and I work as an accountant for a small trading company. Most of my day involves checking invoices and making sure payments go out on time. Once a month, I prepare a short financial report for the management team, which they use to plan the next month's budget. I like this job because it is structured, but sometimes the end of the financial year is very stressful, since everything has to be ready for the auditors.",
  },
];

export const DIAGNOSTIC_ITEMS_B: DiagnosticItem[] = [
  // --- Grammar (12) — те же уровни/сложность, что Form A, item за item ---
  {
    id: "b-grammar-be",
    skill: "GRAMMAR",
    targetLevel: "A1",
    difficulty: 1,
    topic: "be-verb",
    diagnosticObjective: "Present simple of 'to be' — first person singular",
    promptEn: "I ___ a student.",
    optionsEn: ["am", "is", "are", "be"],
    correctOptionIndex: 0,
  },
  {
    id: "b-grammar-have",
    skill: "GRAMMAR",
    targetLevel: "A1",
    difficulty: 1,
    topic: "have-verb",
    diagnosticObjective: "Present simple of 'to have' — third person singular",
    promptEn: "He ___ a new car.",
    optionsEn: ["has", "have", "is", "are"],
    correctOptionIndex: 0,
  },
  {
    id: "b-grammar-present-simple",
    skill: "GRAMMAR",
    targetLevel: "A2",
    difficulty: 2,
    topic: "present-simple",
    diagnosticObjective: "Present simple negative form",
    promptEn: "She ___ coffee in the morning.",
    optionsEn: ["doesn't drink", "don't drink", "isn't drink", "not drinks"],
    correctOptionIndex: 0,
  },
  {
    id: "b-grammar-present-continuous",
    skill: "GRAMMAR",
    targetLevel: "A2",
    difficulty: 2,
    topic: "present-continuous",
    diagnosticObjective: "Present continuous for a fixed future arrangement",
    promptEn: "We ___ our manager next Monday.",
    optionsEn: ["are meeting", "meet", "met", "meets"],
    correctOptionIndex: 0,
  },
  {
    id: "b-grammar-past-simple",
    skill: "GRAMMAR",
    targetLevel: "A2",
    difficulty: 2,
    topic: "past-simple",
    diagnosticObjective: "Past simple, regular verb",
    promptEn: "They ___ the report yesterday afternoon.",
    optionsEn: ["finish", "finished", "finishes", "finishing"],
    correctOptionIndex: 1,
  },
  {
    id: "b-grammar-future-simple",
    skill: "GRAMMAR",
    targetLevel: "B1",
    difficulty: 3,
    topic: "future-simple",
    diagnosticObjective: "Future simple ('will') for a prediction",
    promptEn: "I think it ___ tomorrow.",
    optionsEn: ["will rain", "rains", "rained", "raining"],
    correctOptionIndex: 0,
  },
  {
    id: "b-grammar-modals-advice",
    skill: "GRAMMAR",
    targetLevel: "B1",
    difficulty: 3,
    topic: "modals",
    diagnosticObjective: "Modal verb for advice ('should')",
    promptEn: "You ___ speak to your manager about the problem.",
    optionsEn: ["should", "must not", "can't", "were"],
    correctOptionIndex: 0,
  },
  {
    id: "b-grammar-superlatives",
    skill: "GRAMMAR",
    targetLevel: "B1",
    difficulty: 3,
    topic: "comparatives",
    diagnosticObjective: "Superlative form of a two-syllable adjective",
    promptEn: "This is ___ hotel in the city.",
    optionsEn: ["the busiest", "more busy", "busiest", "the more busy"],
    correctOptionIndex: 0,
  },
  {
    id: "b-grammar-prepositions-place",
    skill: "GRAMMAR",
    targetLevel: "B1",
    difficulty: 3,
    topic: "prepositions",
    diagnosticObjective: "Preposition of place",
    promptEn: "The meeting room is ___ the third floor.",
    optionsEn: ["on", "in", "at", "under"],
    correctOptionIndex: 0,
  },
  {
    id: "b-grammar-present-perfect",
    skill: "GRAMMAR",
    targetLevel: "B1",
    difficulty: 4,
    topic: "present-perfect",
    diagnosticObjective: "Present perfect with 'already' for a completed action",
    promptEn: "We ___ already sent the invoice.",
    optionsEn: ["have", "has", "had", "having"],
    correctOptionIndex: 0,
  },
  {
    id: "b-grammar-second-conditional",
    skill: "GRAMMAR",
    targetLevel: "B2",
    difficulty: 5,
    topic: "conditionals",
    diagnosticObjective: "Second conditional — unreal present/future situation",
    promptEn: "If I ___ more time, I would learn another language.",
    optionsEn: ["had", "have", "will have", "would have"],
    correctOptionIndex: 0,
  },
  {
    id: "b-grammar-passive-voice",
    skill: "GRAMMAR",
    targetLevel: "B2",
    difficulty: 4,
    topic: "passive-voice",
    diagnosticObjective: "Past passive voice",
    promptEn: "The contract ___ last week.",
    optionsEn: ["was signed", "signed", "has sign", "is signing"],
    correctOptionIndex: 0,
  },

  // --- Vocabulary (10) — те же уровни/сложность, другой контент --------
  {
    id: "b-vocab-small-synonym",
    skill: "VOCABULARY",
    targetLevel: "A1",
    difficulty: 1,
    topic: "everyday-synonyms",
    diagnosticObjective: "Basic adjective synonym",
    promptEn: "Choose the word closest in meaning to 'small'.",
    optionsEn: ["little", "huge", "fast", "loud"],
    correctOptionIndex: 0,
  },
  {
    id: "b-vocab-pharmacy",
    skill: "VOCABULARY",
    targetLevel: "A1",
    difficulty: 1,
    topic: "everyday-vocabulary",
    diagnosticObjective: "Everyday place vocabulary",
    promptEn: "A place where you buy medicine is called a ___.",
    optionsEn: ["pharmacy", "bakery", "garage", "cinema"],
    correctOptionIndex: 0,
  },
  {
    id: "b-vocab-submit",
    skill: "VOCABULARY",
    targetLevel: "A2",
    difficulty: 2,
    topic: "study-vocabulary",
    diagnosticObjective: "Study-related verb in context",
    promptEn: "Students must ___ their essays before Friday.",
    optionsEn: ["submit", "waste", "lose", "paint"],
    correctOptionIndex: 0,
  },
  {
    id: "b-vocab-summarise",
    skill: "VOCABULARY",
    targetLevel: "A2",
    difficulty: 2,
    topic: "study-vocabulary",
    diagnosticObjective: "Academic verb synonym",
    promptEn: "Choose the word closest in meaning to 'sum up'.",
    optionsEn: ["summarise", "hide", "forget", "ignore"],
    correctOptionIndex: 0,
  },
  {
    id: "b-vocab-rescheduled",
    skill: "VOCABULARY",
    targetLevel: "B1",
    difficulty: 3,
    topic: "professional-vocabulary",
    diagnosticObjective: "Workplace verb in context",
    promptEn: "The interview has been ___ to next Tuesday.",
    optionsEn: ["rescheduled", "attended", "opened", "painted"],
    correctOptionIndex: 0,
  },
  {
    id: "b-vocab-enclosed",
    skill: "VOCABULARY",
    targetLevel: "B1",
    difficulty: 3,
    topic: "business-correspondence",
    diagnosticObjective: "Formal email phrasing",
    promptEn: "Please find ___ a copy of the contract.",
    optionsEn: ["enclosed", "enclosing", "enclose", "enclosure"],
    correctOptionIndex: 0,
  },
  {
    id: "b-vocab-expenditure",
    skill: "VOCABULARY",
    targetLevel: "B1",
    difficulty: 3,
    topic: "financial-vocabulary",
    diagnosticObjective: "Basic financial term in context",
    promptEn: "The company's ___ increased due to new equipment purchases.",
    optionsEn: ["expenditure", "weather", "traffic", "weight"],
    correctOptionIndex: 0,
  },
  {
    id: "b-vocab-solvent",
    skill: "VOCABULARY",
    targetLevel: "B2",
    difficulty: 4,
    topic: "financial-vocabulary",
    diagnosticObjective: "Financial adjective synonym",
    promptEn: "Choose the word closest in meaning to 'financially stable'.",
    optionsEn: ["solvent", "bankrupt", "famous", "generous"],
    correctOptionIndex: 0,
  },
  {
    id: "b-vocab-deficit",
    skill: "VOCABULARY",
    targetLevel: "B2",
    difficulty: 4,
    topic: "financial-vocabulary",
    diagnosticObjective: "Financial antonym",
    promptEn: "The opposite of 'surplus' is ___.",
    optionsEn: ["deficit", "income", "revenue", "asset"],
    correctOptionIndex: 0,
  },
  {
    id: "b-vocab-negotiate-term",
    skill: "VOCABULARY",
    targetLevel: "B2",
    difficulty: 4,
    topic: "business-vocabulary",
    diagnosticObjective: "Business verb synonym",
    promptEn: "Choose the word closest in meaning to 'discuss terms to reach an agreement'.",
    optionsEn: ["negotiate", "ignore", "cancel", "deliver"],
    correctOptionIndex: 0,
  },

  // --- Reading (2 passages × 3 questions) --------------------------------
  {
    id: "b-reading-library-q1",
    skill: "READING",
    targetLevel: "A2",
    difficulty: 2,
    topic: "reading-main-idea",
    diagnosticObjective: "Main idea comprehension",
    passageId: "b-reading-library-orientation",
    promptEn: "What is this text mainly about?",
    optionsEn: [
      "An orientation session and general information about the library",
      "A list of exam dates",
      "Instructions for teachers",
      "A history of the library building",
    ],
    correctOptionIndex: 0,
  },
  {
    id: "b-reading-library-q2",
    skill: "READING",
    targetLevel: "A2",
    difficulty: 2,
    topic: "reading-specific-info",
    diagnosticObjective: "Scanning for specific information",
    passageId: "b-reading-library-orientation",
    promptEn: "What must students bring to borrow books?",
    optionsEn: ["Their student card", "A library map", "A laptop", "Cash"],
    correctOptionIndex: 0,
  },
  {
    id: "b-reading-library-q3",
    skill: "READING",
    targetLevel: "B1",
    difficulty: 3,
    topic: "reading-inference",
    diagnosticObjective: "Inference — combining two details from the text",
    passageId: "b-reading-library-orientation",
    promptEn: "What can a student do if they cannot attend the Thursday session?",
    optionsEn: [
      "Book an individual tour at the front desk",
      "Wait until next year",
      "Send an email to the library director",
      "Ask a classmate to attend instead",
    ],
    correctOptionIndex: 0,
  },
  {
    id: "b-reading-expansion-q1",
    skill: "READING",
    targetLevel: "B1",
    difficulty: 3,
    topic: "reading-main-idea",
    diagnosticObjective: "Main idea comprehension in a professional text",
    passageId: "b-reading-company-expansion",
    promptEn: "What is this news report mainly about?",
    optionsEn: [
      "A logistics company's plan to open new distribution centres",
      "A new law about transport safety",
      "A company that is closing its offices",
      "An interview with a company driver",
    ],
    correctOptionIndex: 0,
  },
  {
    id: "b-reading-expansion-q2",
    skill: "READING",
    targetLevel: "B1",
    difficulty: 3,
    topic: "reading-specific-info",
    diagnosticObjective: "Scanning for a cause-and-effect detail",
    passageId: "b-reading-company-expansion",
    promptEn: "Why is the company expanding?",
    optionsEn: ["Customer demand grew faster than expected", "Fuel costs fell", "The government offered a subsidy", "Competitors closed down"],
    correctOptionIndex: 0,
  },
  {
    id: "b-reading-expansion-q3",
    skill: "READING",
    targetLevel: "B2",
    difficulty: 4,
    topic: "reading-inference",
    diagnosticObjective: "Inference about future risk from context",
    passageId: "b-reading-company-expansion",
    promptEn: "What can be inferred about the company's expansion plans?",
    optionsEn: [
      "Rising fuel costs could require additional investment",
      "The expansion has already been cancelled",
      "The company no longer needs new staff",
      "Analysts are fully confident about the plan",
    ],
    correctOptionIndex: 0,
  },

  // --- Listening (2 scripts × 2 questions) -------------------------------
  {
    id: "b-listening-library-q1",
    skill: "LISTENING",
    targetLevel: "A2",
    difficulty: 2,
    topic: "listening-gist",
    diagnosticObjective: "Listening for gist",
    passageId: "b-listening-library-hours",
    promptEn: "What is this announcement mainly about?",
    optionsEn: [
      "A temporary change to the library's closing time",
      "A new library building",
      "A change of librarian",
      "A library holiday closure",
    ],
    correctOptionIndex: 0,
  },
  {
    id: "b-listening-library-q2",
    skill: "LISTENING",
    targetLevel: "A2",
    difficulty: 2,
    topic: "listening-detail",
    diagnosticObjective: "Listening for a specific detail",
    passageId: "b-listening-library-hours",
    promptEn: "Until what time is the help desk open today?",
    optionsEn: ["4:30 pm", "5 pm", "9 pm", "6 pm"],
    correctOptionIndex: 0,
  },
  {
    id: "b-listening-accountant-q1",
    skill: "LISTENING",
    targetLevel: "B1",
    difficulty: 3,
    topic: "listening-gist",
    diagnosticObjective: "Listening for gist in a professional monologue",
    passageId: "b-listening-accountant",
    promptEn: "What does Marcus do in his job?",
    optionsEn: [
      "He checks invoices and prepares financial reports",
      "He drives delivery trucks",
      "He manages a sales team",
      "He designs company software",
    ],
    correctOptionIndex: 0,
  },
  {
    id: "b-listening-accountant-q2",
    skill: "LISTENING",
    targetLevel: "B1",
    difficulty: 3,
    topic: "listening-detail",
    diagnosticObjective: "Listening for a specific detail",
    passageId: "b-listening-accountant",
    promptEn: "When does Marcus say his job becomes very stressful?",
    optionsEn: ["The end of the financial year", "The start of the month", "During client meetings", "During summer holidays"],
    correctOptionIndex: 0,
  },
];

export function getItemsForSkillB(skill: DiagnosticItem["skill"]): DiagnosticItem[] {
  return DIAGNOSTIC_ITEMS_B.filter((i) => i.skill === skill);
}

export function findItemB(id: string): DiagnosticItem | undefined {
  return DIAGNOSTIC_ITEMS_B.find((i) => i.id === id);
}

export function findPassageB(id: string): DiagnosticPassage | undefined {
  return DIAGNOSTIC_PASSAGES_B.find((p) => p.id === id);
}

export const TOTAL_DIAGNOSTIC_ITEMS_B = DIAGNOSTIC_ITEMS_B.length;
